version: 3.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.Log4Net\Elmah.Io.Log4Net.csproj --output artifacts
test:
  assemblies:
    only:
    - test\Elmah.Io.Log4Net.Test\bin\**\Elmah.Io.Log4Net.Test.dll
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: F5CTc3/bSmMHKRW3d4pOSQu5roNE4RNb4wspqcdWDt8nCd3x2hR7nDAYEywofdn+
notifications:
- provider: Slack
  auth_token:
    secure: Ec+xQWO7tydVydZglSYdntEN5vhti5g5fUmXE+lIYT+CusdHW9QNi3QcJzJU7p76F8O3jb5x+2gFWvuNZLOWkg==
  channel: '#builds'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true